version: '3.8'
services:
  checkbook-api:
    build: ./checkbook-api
    ports: 
      - "8443:8443"
    depends_on: 
      - mysql  
  mysql:
    image: mariadb:10.5.8
    env_file:
      - ./env/mysql.env
    ports:
      - '3306:3306'
    volumes:
      - data:/var/lib/mysql    
  checkbook-react-frontend:
    build: ./checkbook-ui
    ports: 
      - "443:3000"
    depends_on:
      - checkbook-api
volumes:
  data:  