version: '3.8'
services:
  checkbook-api:
    build: ./checkbook-api
    ports: 
      - "8080:8080"
    depends_on: 
      - mysql  
  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
    ports:
      - '3306:3306'
    volumes:
      - data:/var/lib/mysql    
  # react-frontend:
volumes:
  data:  